name:                chassis
version:             0.0.2.0
git:                 https://gitlab.com/homotopic-tech/chassis
license:             MIT
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Prelude with algebraic constructs and polykinds on.
category:            Prelude

dependencies:
- base >= 4.7 && < 5
- bytestring
- comonad
- composite-base
- containers
- contravariant
- distributive
- either
- exceptions
- extra
- first-class-families
- path
- profunctors
- rio
- text
- time
- vinyl

library:
  source-dirs: src
